#!/usr/bin/env bash
#Prints "Best School" 10 times and "hi" on the 9th "Best School"
count=1
while [ $count -le 10 ]; do
	if [ $count -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((count++))
done
