#!/usr/bin/env bash
#Prints "bad luck" on 4th loop, "good luck" on 8th loop and "Best School" on other loops
count=1
while [ $count -le 10 ]; do
	if [ $count -eq 4 ]; then
		echo "bad luck"
	elif [ $count -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((count++))
done
